project:
  type: website
  title: "Buku Panduan Akademik"
  output-dir: docs
  
website:
  title: "Buku Panduan Akademik"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar: 
    style: docked
    search: true
    contents: 
      - index.qmd
      - susunantim.qmd
      - pendahuluan.qmd
      - sarpras.qmd
      - ketentuan.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    number-sections: false
editor: visual
