project:
  type: book
  title: "Buku Panduan Akademik"
  output-dir: docs
  
book:
  title: "Buku Panduan Akademik"
  subtitle: "Kurikulum 2022"
  site-url: https://psikologi-yarsi.github.io/panduanakademik
  sidebar: 
    logo: "logo.png"
    style: docked
    search: true
  chapters: 
    - index.qmd
    - pendahuluan.qmd
    - sarpras.qmd
    - ketentuan.qmd
    - kurikulum.qmd
    - susunantim.qmd
  page-navigation: true
  
format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    number-sections: false
    title-block-banner: true
    toc-title: "Di Halaman Ini:"
    lang: id
    
editor: visual
