project:
  type: website
  title: "Buku Panduan Akademik"
  output-dir: docs
  
website:
  title: "Buku Panduan Akademik"
  sidebar: 
    style: docked
    search: true
    contents: 
      - index.qmd
      - pendahuluan.qmd
      - sarpras.qmd
      - ketentuan.qmd
      - kurikulum.qmd
      - susunantim.qmd
  bread-crumbs: true
  
format:
  html:
    theme:
      - yeti
    css: styles.css
    toc: true
    number-sections: false
    title-block-banner: true
    toc-title: "Di Halaman Ini:"
editor: visual
