# KATA SAMBUTAN {.unnumbered}

Assalamu alaikum Wr. Wb.

Puji syukur ke hadirat Illahi Robbi karena Fakultas Psikologi Universitas YARSI dari sejak berdiri di tahun 2007 sampai sekarang telah mengalami perkembangan dan semakin memantapkan posisinya sebagai salah satu Fakultas Psikologi yang layak diperhitungkan. Untuk itu, terutama bagi para mahasiswa baru kami mengucapkan selamat datang, selamat bergabung sebagai anggota baru keluarga Fakultas Psikologi Universitas YARSI.

Buku ini adalah buku panduan bagi para mahasiwa yang antara lain berisi rangkaian mata kuliah yang akan diikuti. Dengan mencermati rangkaian mata kuliah yang ada dalam buku panduan ini, maka para mahasiswa dapat mengantisipasi diri terhadap pemanfaatan energi fisik dan psikisnya agar terarah dan terencana dengan seoptimal mungkin. Untuk memudahkan pencapaian tersebut, mahasiswa memiliki dosen pembimbing akademik yang akan membantu memberikan saran dan masukan terhadap kegiatan akademis maupun non akademis.

Sekali lagi kami ucapkan selamat datang di Fakultas Psikologi Universitas YARSI. Marilah kita jalin tali silaturahmi dengan erat dan hangat dengan seluruh sivitas akademika, sehingga kerjasama di antara para mahasiswa, dosen, serta seluruh staf akademik dapat terjalin dengan baik, demi optimalisasi prestasi mengajar di fakultas tercinta ini.

Akhirul kata, selamat belajar dan semoga sukses.

Wassalamu alaikum Wr. Wb.

```{=html}
<p style="text-align: right;">Jakarta, September 2022</p>
<p style="text-align: right;">&nbsp;</p>
<p style="text-align: right;"><strong>Dr. Miwa Patnani, M.Si., Psikolog </strong></p>
<p style="text-align: right;">Dekan</p>
```
