# KETENTUAN AKADEMIK {.unnumbered}

## **Pembimbing Akademik**

Pembimbing Akademik (PA) adalah dosen tetap fakultas yang sedang tidak tugas belajar, yang ditunjuk oleh Pimpinan Fakultas untuk : 

1.  Memberikan pengarahan kepada mahasiswa tentang :

    a.  Penyusunan rencana studinya sampai lulus;
    b.  Pengisian KRS/KPRS;
    c.  Penjelasan kebijakan studi, yaitu memberikan pertimbangan tentang banyaknya beban studi yang dapat diambil pada semester berikutnya, serta pertimbangan program MBKM yang akan dipilih oleh mahasiswa;

2.  Membantu, mengamati, dan atau mengarahkan serta memacu kelancaran studi mahasiswa dalam hal:

    a.  Mengusahakan kelancaran mengikuti perkuliahan
    b.  Memilih teknik mengikuti perkuliahan
    c.  Menggunakan kepustakaan dan teknik membaca buku
    d.  Mengenalkan sumber-sumber belajar
    e.  Pengaturan waktu yang tepat
    f.  Mencatat perkembangan belajar secara berkala
    g.  Menyampaikan informasi mengenai mahasiswa tertentu yang mengalami hambatan studi kepada dosen mata kuliah.

3.  Memberikan bantuan terhadap masalah-masalah yang berhubungan dengan kepribadian mahasiswa (penyesuaian lingkungan, watak, dan lain- lain);

4.  Memberikan pertimbangan penyelesaian studi mahasiswa kepada Pimpinan Fakultas.

Pembimbing Akademik (PA) adalah pembimbing mahasiswa dalam mengatur strategi pengambilan mata kuliah, berdasarkan kurikulum yang berlaku dan prestasi akademik, dengan pertimbangan-pertimbangan, antara lain:

a.  Prasyarat setiap mata kuliah;
b.  Keterkaitan antara satu mata kuliah dengan mata kuliah yang lain, meskipun tidak merupakan prasyarat.
c.  Pemilihan mata kuliah pilihan sesuai dengan kompetensi yang diminati.
d.  Kemampuan mahasiswa, ditinjau dari Indeks Prestasi Semester yang dicapai pada semester sebelumnya.

Pembimbing Akademik (PA) memberikan peringatan kepada mahasiswa yang berdasarkan perkiraan mempunyai masalah dengan batas masa studi.

::: callout-important
**Mahasiswa diwajibkan melakukan pertemuan pembimbingan akademik dua kali pada setiap semester (sebelum pengisian KRS dan setelah UTS).**
:::

## **Cuti Akademik**

Cuti akademik adalah cuti di mana mahasiswa dibebaskan dari kewajiban mengikuti semua kegiatan akademik dan lama masa cuti tidak dihitung dalam masa studi. Mahasiswa yang mengajukan permohonan cuti akademik hendaknya memperhatikan rencana studinya yang disusun bersama PA masing-masing. Mahasiswa juga memiliki kewajiban untuk membayar uang semester sebesar 30% dari total uang semester untuk bisa mengambil cuti akademik. 

Alasan cuti akademik yang dapat diterima adalah : 

1.  Faktor kesehatan

    Mahasiswa yang bersangkutan harus istirahat efektif selama satu semester atau lebih dengan melampirkan surat keterangan dokter. 

2.  Faktor lain yang dapat dipertimbangkan, dengan melampirkan surat keterangan atau rekomendasi dari pejabat yang berwenang dan/atau orangtua/wali mahasiswa. 

::: callout-important
**Jangka waktu cuti akademik paling banyak adalah 2 semester dan tidak dapat diambil secara berturut-turut.**
:::

Tahapan pengajuannya adalah : 

1.  Mahasiswa berkonsultasi kepada PA untuk mengambil cuti akademik.
2.  Mahasiswa mengambil formulir permohonan cuti akademik
3.  Mahasiswa menyerahkan formulir permohonan cuti akademik yang telah diisi dengan persetujuan dari Orang Tua/wali dan PA serta diketahui Bagian Akademik dan Perpustakaan, paling lambat satu bulan setelah perkuliahan berjalan.
4.  Mahasiswa mendapat surat persetujuan cuti akademik yang telah ditandatangani oleh Wadek I dan Dekan
5.  Mahasiswa menjalani cuti yang telah disetujui Dekan.
6.  Mahasiswa yang telah menyelesaikan cuti akademik melapor kepada Kepala Program Studi kemudian melakukan pendaftaran ulang mahasiswa lama.

## **Mahasiswa non aktif**

Mahasiswa non aktif adalah mahasiswa yang mempunyai NPM namun: (1) tidak melakukan pendaftaran ulang; tidak mengajukan cuti akademik; (2) melakukan registrasi namun tidak mengikuti kegiatan akademik selama lima minggu berturut-turut. Masa non aktif dihitung sebagai masa studi.

::: callout-important
**Mahasiswa yang non aktif lebih dari 2 (dua) semester, maka mahasiswa tersebut dinyatakan berhenti dan tidak diperkenankan melanjutkan studi sebagai mahasiswa lama di Universitas YARSI.**
:::

Mahasiswa yang telah non aktif setelah 1 semester, untuk kembali menjadi mahasiswa aktif, wajib: 

1.  Mengajukan surat permohonan untuk kembali aktif kepada Wadek I
2.  Melunasi kewajiban keuangan selama tidak aktif
3.  Melakukan pendaftaran ulang mahasiswa lama

## **Pengunduran Diri**

1.  Mahasiswa berkonsultasi kepada PA berkenaan dengan rencana pengunduran diri.
2.  Mahasiswa mengambil formulir permohonan pengunduran diri.
3.  Mahasiswa mengisi formulir permohonan pengunduran diri dengan persetujuan dari Orang Tua, PA, dan Dekan serta diketahui oleh Bagian Akademik dan Perpustakaan. Formulir permohonan pengunduran diri dilampiri surat keterangan dari orang tua/wali.
4.  Mahasiswa mendapat formulir permohonan pengunduran diri asli yang telah diisi lengkap.
5.  Mahasiswa mendapat transkrip akademik sampai semester terakhir aktif.

## **Mahasiswa Putus Kuliah**

Untuk menghindari kegagalan setelah bertahun-tahun belajar dengan biaya yang cukup besar maka dilakukan suatu mekanisme di mana mahasiswa diberikan peringatan-peringatan tentang hasil studi sebelum mereka dinyatakan putus kuliah (*drop out*/DO).

Sebelum sampai pada keputusan putus kuliah, mahasiswa berhak mendapat peringatan, dengan ketentuan sebagaimana diatur dalam SK Dekan. Ketentuan tersebut adalah sebagai berikut:

1.  Mahasiswa akan diberikan surat peringatan putus kuliah apabila :

    a.  **Pada akhir tahun pertama (semester II)**, mahasiswa mendapat peringatan lisan dan tertulis apabila tidak mampu mencapai rata-rata IPK minimal 2,00.
    b.  **Pada akhir tahun kedua (semester IV)**, mahasiswa mendapat peringatan lisan dan tertulis apabila tidak mampu mencapai rata-rata minimal IPK 2,00.
    c.  **Pada akhir tahun ketiga (semester VI)**, mahasiswa mendapat peringatan lisan dan tertulis apabila tidak mampu mencapai rata-rata minimal IPK 2,00.
    d.  **Pada akhir tahun keempat (semester VIII)**, mahasiswa mendapat peringatan lisan dan tertulis apabila tidak mampu mencapai rata-rata minimal IPK 2,00.
    e.  Belum dinyatakan lulus **setelah masa studi 12 semester**.

2.  Mahasiswa yang dinyatakan terancam putus kuliah akan mendapatkan peringatan, dengan ketentuan sebagi berikut: 

    a.  Untuk peringatan ke-1 dan ke-2, memanggil mahasiswa beserta orangtua untuk mendapat penjelasan dan peringatan tentang perkembangan hasil studi mahasiswa tersebut. Pemanggilan ini dilakukan di awal semester ganjil maupun genap tahun ajaran berlangsung.
    b.  Untuk peringatan ke-3, memanggil mahasiswa dan orang tua untuk bersedia mengundurkan diri dari Fakultas Psikologi Universitas YARSI. Bilamana tidak bersedia, Fakultas akan mengambil langkah kebijakan mengeluarkan surat putus kuliah (DO).

Sesuai dengan ketentuan, batas masa studi maksimal untuk menyelesaikan pendidikan di Fakultas Psikologi adalah 14 semester dengan cuti akademik maksimal 2 semester yang tidak dapat diambil berturut-turut.

## **Ketentuan Jumlah SKS**

Ketentuan jumlah SKS yang diizinkan berdasarkan Indeks Prestasi Semester (IPS) yang diperoleh pada semester sebelumnya adalah sebagai berikut:

| Indeks Prestasi Semester | Jumlah SKS Maksimum |
|:------------------------:|:-------------------:|
|         \< 1,50          |         12          |
|       1,50 - 1,99        |         16          |
|       2,00 - 2,49        |         18          |
|       2,50 - 2,75        |         20          |
|       2,76 - 3,00        |         22          |
|         \> 3,00          |         24          |

## **Pengisian KPRS**

Satu pekan setelah perkuliahan berjalan, mahasiswa diberi kesempatan untuk menambah, mengurangi atau mengganti mata kuliah dalam KRS. Kartu Perbaikan Rencana Studi (KPRS) harus mendapat persetujuan PA. Tahapan yang harus diikuti adalah sebagai berikut:

1.  Memperhatikan jadwal mengisi KPRS sesuai dengan jadwal yang telah ditentukan.
2.  Mengisi KPRS di SISAKAD dan meminta persetujuan PA. 
3.  Mencetak KPRS yang telah disetujui PA dan memberikan salinannya kepada bagian Akademik dan PA pada saat yang ditentukan. 

## **Perkuliahan dan Praktikum**

1.  Perencanaan, penyusunan, dan pelaksanaan kurikulum pendidikan menggunakan sistem kredit sebagai tolak ukur beban akademik mahasiswa. 
2.  Sistem kredit adalah suatu sistem penyelenggaraan program pendidikan yang dinyatakan dalam sks, dengan ukuran waktu terkecil adalah satu semester. 
3.  Semester adalah satuan waktu kegiatan pendidikan selama 16 pekan, terdiri atas 14 pekan (tatap muka) kegiatan perkuliahan/praktikum, satu pekan kegiatan Ujian Tengan Semester (UTS), dan satu pekan kegiatan Ujian Akhir Semester (UAS). 
4.  1 SKS dalam bentuk pembelajaran kuliah, responsi, dan tutorial, mencakup: 
    -   50 menit kegiatan tatap muka di kelas dengan pengajar, 
    -   60 menit kegiatan terstruktur seperti mengerjakan tugas, soal-soal dari pengajar dll, 
    -   60 menit kegiatan mandiri guna pengayaan seperti mengunjungi perpustakaan, belajar mandiri, belajar kelompok dan lain-lain. 
5.  Khusus untuk mata kuliah seminar, dan bentuk pembelajaran lain, satu sks setara dengan 170 menit kegiatan per minggu, yang terdiri dari 100 menit per minggu per semester, dan kegiatan belajar mandiri 70 menit per minggu per semester. 
6.  Satu tahun akademik terdiri atas 2 semester. Semester merupakan satuan waktu pembelajaran efektif selama paling sedikit enam belas (16) minggu, termasuk ujian tengah semester dan akhir semester. 
7.  Universitas YARSI dapat menyelenggarakan semester antara, dengan ketentuan diselenggarakan: 
    a.  Paling sedikit 8 minggu; 

    b.  Beban belajar mahasiswa paling banyak 9 sks; 

    c.  Apabila dalam bentuk perkuliahan, tatap muka paling sedikit enam belas kali (16) termasuk ujian tengah semester antara dan ujian akhir semester antara. 

## **Absensi Perkuliahan**

Mahasiswa diwajibkan untuk mengisi absensi perkuliahan. Mahasiswa diwajibkan untuk menghadiri perkuliahan dan tercatat di absensi yang kemudian disahkan oleh Pusat Pelayanan Terpadu (PLT) minimal 11 pertemuan dan maksimal 14 pertemuan. Keteledoran yang diakibatkan karena lupa mengisi absensi akan menjadi tanggung jawab mahasiswa, hal ini dapat berkonsekuensi pada: 

1.  Dihitung sebagai ketidakhadiran. 
2.  Mahasiswa tidak dapat mengikuti ujian akhir semester

## **Ujian**

Secara umum, penilaian/evaluasi mata kuliah meliputi empat komponen, yaitu kuis, tugas, UTS dan UAS. Tugas diatur oleh masing-masing dosen, sedangkan UTS dan UAS diselenggarakan oleh lembaga. 

Prosedur penyelenggaran UTS relatif sama dengan prosedur penyelenggaraan UAS, yaitu: 

1.  Penyelenggaraan ujian sesuai dengan jadwal dan tempat yang telah ditetapkan oleh SBAAK. 
2.  SBAAK dapat melakukan perubahan jadwal dan tempat ujian dengan seijin KPS terkait. 
3.  Kesalahan membaca jadwal atau tempat ujian, **tidak dapat** digunakan sebagai alasan untuk meminta ujian khusus/susulan. 
4.  Mahasiswa yang ujiannya bentrok dengan mata kuliah lain harus melapor ke PLT untuk penentuan jadwal ujian susulan. 
5.  Mahasiswa diperbolehkan untuk mengikuti Ujian Akhir Semester (UAS) jika sudah memenuhi kriteria kehadiran 80% dalam perkuliahan. 

## **Ujian Susulan**

Ujian susulan hanya diberikan kepada mahasiswa yang berhak mengikuti ujian tetapi tidak dapat mengikuti ujian karena mengalami kondisi di bawah ini: 

1.  Pihak Keluarga inti, termasuk kakek/nenek meninggal. Syarat pengajuan ujian : 
    a.  Mengisi form permohonan ujian susulan kepada Pusat Pelayanan Terpadu (PLT) dilampiri fotokopi surat kematian dari RT/RW. 
    b.  Membawa Kartu Ujian. 
2.  Menderita sakit. Syarat pengajuan ujian : 
    a.  Mengisi form permohonan ujian kepada PLT dilampiri surat keterangan sakit dari dokter (asli). 
    b.  Membawa Kartu Ujian. 
3.  Paling lambat 1 (satu) pekan setelah pengajuan permohonan, mahasiswa dapat melakukan jadwal ujian susulan. 
4.  Mahasiswa melaksanakan ujian sesuai jadwal yang ditentukan. 

## **Prestasi Akademik**

Secara umum penilaian/evaluasi mata kuliah ada empat komponen yaitu kuis, tugas mandiri/kelompok, UTS dan UAS. Kuis, tugas mandiri/kelompok diatur oleh masing-masing dosen, sedangkan UTS dan UAS diselenggarakan oleh lembaga. 

Keberhasilan mahasiswa menempuh suatu mata kuliah harus ditentukan atas dasar sekurang-kurangnya dua kali evaluasi, yaitu UTS dan UAS. Jenis evaluasi dan cara melakukannya disesuaikan dengan sifat mata kuliah. Dalam hal digunakan lebih dari satu jenis evaluasi, tiap jenis evaluasi (Tugas/UTS/UAS) pada data evaluasi keseluruhan diwujudkan dalam bentuk pembobotan. Jenis evaluasi harus mencerminkan ciri mata kuliah yang bersangkutan dan tergantung pada dosennya masing-masing. 

Nilai mata kuliah diperoleh dari hasil evaluasi belajar yang dilakukan oleh dosen pengampu mata kuliah terhadap peserta mata kuliah. Evaluasi belajar dilakukan dalam berbagai bentuk, disesuaikan dengan tujuan belajar dari masing-masing mata kuliah. Dalam setiap mata kuliah, setidaknya dilakukan 4 (empat) kali evaluasi, yaitu: 

1.  Kuis atau yang setara, minimal diselenggarakan 1 kali dalam satu semester, 
2.  Tugas, baik individu maupun kelompok. Tugas dapat berupa tugas mingguan maupun tugas akhir. Tugas dapat disesuaikan dengan tujuan perkuliahan, dapat berupa membuat ringkasan bacaan, projek, makalah, dan lainnya. 
3.  Ujian Tengah Semester, diselengarakan di minggu ke-8 setelah semester berjalan. UTS dapat diselenggarakan jika jumlah pertemuan tatap muka di kelas telah mencapai minimal 6 (enam) pertemuan. 
4.  Ujian Akhir Semester, diselenggarakan di akhir semester. UAS dapat diselenggarakan jika jumlah pertemuan tatap muka di kelas telah mencapai 14 (empat belas) pertemuan. 

Nilai akhir mahasiswa untuk setiap mata kuliah diperoleh dari nilai akumulasi evaluasi belajar sebagaimana disebutkan di atas, yang terdiri dari komponen proses dan juga hasil belajar. Adapun bobot masing-masing komponen penilaian telah ditetapkan sebagai berikut: 

1.  Untuk mata kuliah yang bersifat teoretis, terdiri dari ujian tulis (40%), peforma mingguan dan sikap kerja (60%). 
2.  Untuk mata kuliah yang bersifat praktikum, terdiri dari ujian tulis (20%), praktikum (60%), dan performa mingguan serta sikap kerja (20%). 

Nilai sebagaimana diperoleh dari perhitungan di atas disebut nilai mentah. Nilai mentah tersebut dikonversikan ke dalam nilai huruf. Untuk *range* nilai ditentukan oleh Program Studi, adapun konversi nilai angka ke nilai huruf didasarkan pada SK Rektor No. 003/REK/PER/IV/2017 dengan penjelasan sebagai berikut: 

```{=html}

<table style="height: 389px;" width="556">
<tbody>
<tr>
<td style="width: 132px; text-align: center;" colspan="3">Rentang Nilai<br /><br /><br /></td>
<td style="width: 132px; text-align: center;" rowspan="2">Kategori<br /><br /></td>
</tr>
<tr>
<td style="width: 132px; text-align: center;">Range</td>
<td style="width: 132px; text-align: center;">Angka</td>
<td style="width: 132px; text-align: center;">Huruf</td>
</tr>
<tr>
<td style="width: 132px; text-align: center;">85,00 - 100</td>
<td style="width: 132px; text-align: center;">4,00</td>
<td style="width: 132px; text-align: center;">A</td>
<td style="width: 132px; text-align: center;">Sangat Baik</td>
</tr>
<tr>
<td style="width: 132px; text-align: center;">80,00 - 84,49</td>
<td style="width: 132px; text-align: center;">3,75</td>
<td style="width: 132px; text-align: center;">A-</td>
<td style="width: 132px; text-align: center;">Baik</td>
</tr>
<tr>
<td style="width: 132px; text-align: center;">75,00 - 79,99</td>
<td style="width: 132px; text-align: center;">3,50</td>
<td style="width: 132px; text-align: center;">AB</td>
<td style="width: 132px; text-align: center;">Baik</td>
</tr>
<tr>
<td style="width: 132px; text-align: center;">70,00 - 74,99</td>
<td style="width: 132px; text-align: center;">3,25</td>
<td style="width: 132px; text-align: center;">B+</td>
<td style="width: 132px; text-align: center;">Baik</td>
</tr>
<tr>
<td style="width: 132px; text-align: center;">65,00 - 69,99</td>
<td style="width: 132px; text-align: center;">3,00&nbsp;</td>
<td style="width: 132px; text-align: center;">B&nbsp;</td>
<td style="width: 132px; text-align: center;">Baik</td>
</tr>
<tr>
<td style="width: 132px; text-align: center;">60,00 - 64,49</td>
<td style="width: 132px; text-align: center;">2,75&nbsp;</td>
<td style="width: 132px; text-align: center;">B-&nbsp;</td>
<td style="width: 132px; text-align: center;">Cukup</td>
</tr>
<tr>
<td style="width: 132px; text-align: center;">55,00 - 59,99</td>
<td style="width: 132px; text-align: center;">2,50&nbsp;</td>
<td style="width: 132px; text-align: center;">BC&nbsp;</td>
<td style="width: 132px; text-align: center;">Cukup</td>
</tr>
<tr>
<td style="width: 132px; text-align: center;">50,00 - 54,49</td>
<td style="width: 132px; text-align: center;">2,25&nbsp;</td>
<td style="width: 132px; text-align: center;">C+&nbsp;</td>
<td style="width: 132px; text-align: center;">Cukup&nbsp;</td>
</tr>
<tr>
<td style="width: 132px; text-align: center;">45,00 - 49,99</td>
<td style="width: 132px; text-align: center;">2,00&nbsp;</td>
<td style="width: 132px; text-align: center;">C&nbsp;</td>
<td style="width: 132px; text-align: center;">Cukup&nbsp;</td>
</tr>
<tr>
<td style="width: 132px; text-align: center;">40,00 - 44,49</td>
<td style="width: 132px; text-align: center;">1,75</td>
<td style="width: 132px; text-align: center;">C-</td>
<td style="width: 132px; text-align: center;">Wajib Mengulang MK</td>
</tr>
<tr>
<td style="width: 132px; text-align: center;">35,00 - 39,99</td>
<td style="width: 132px; text-align: center;">1,50</td>
<td style="width: 132px; text-align: center;">CD</td>
<td style="width: 132px; text-align: center;">Wajib Mengulang MK</td>
</tr>
<tr>
<td style="width: 132px; text-align: center;">30,00 - 34,49</td>
<td style="width: 132px; text-align: center;">1,25</td>
<td style="width: 132px; text-align: center;">D+</td>
<td style="width: 132px; text-align: center;">Wajib Mengulang MK</td>
</tr>
<tr>
<td style="width: 132px; text-align: center;">25,00 - 29,99</td>
<td style="width: 132px; text-align: center;">1,00&nbsp;</td>
<td style="width: 132px; text-align: center;">D&nbsp;</td>
<td style="width: 132px; text-align: center;">Wajib Mengulang MK&nbsp;</td>
</tr>
<tr>
<td style="width: 132px; text-align: center;">0,00 - 24,49</td>
<td style="width: 132px; text-align: center;">0&nbsp;</td>
<td style="width: 132px; text-align: center;">E</td>
<td style="width: 132px; text-align: center;">Wajib Mengulang MK&nbsp;</td>
</tr>
</tbody>
</table>
```

Mahasiswa diberikan kesempatan untuk menentukan mata kuliah yang akan diikuti, dengan memperhatikan persyaratan sebagai berikut: 

1.  Mahasiswa dapat mengikuti mata kuliah lanjutan bila sebelumnya telah mengikuti atau lulus mata kuliah prasyarat sesuai dengan skema kurikulum yang berlaku. 
2.  Mata kuliah dengan nilai TL atau lebih rendah dari C (C-, dst) wajib diperbaiki sebelum mendaftar sidang skripsi. 
3.  Perbaikan dapat dilakukan dengan mengambil MK yang sama pada tahun ajaran berikutnya ataupun pada semester remedial. 
4.  Nilai yang lebih tinggi yang akan dicantumkan dalam KHS. 

## **Indeks Prestasi**

Derajat keberhasilan mahasiswa dalam satu semester dinyatakan dengan IPS (Indeks Prestasi Semester) dan IPK (Indeks Prestasi Kumulatif). IPS adalah prestasi hasil belajar yang diperoleh di semester yang baru saja berlangsung, sedangkan IPK merupakan prestasi hasil pelajar yang diperoleh dari semester pertama hingga semester yang baru saja berjalan. Mahasiswa akan mendapatkan IPK dan IPS tercantum di dalam Kartu Hasil Studi. Rentang Indeks Prestasi berkisar antara 0.00 - 4.00. Semakin tinggi Indeks Prestasi, maka semakin tinggi pula prestasi mahasiswa di bidang akademik. 

## **Prasyarat Mata Kuliah Tugas Akhir**

Mata Kuliah yang merupakan bagian dari Tugas Akhir, meliputi: 

1.  Seminar Proposal Skripsi (2 sks) 
2.  Belajar Di Luar Kampus (20 - 40 sks) 
3.  Skripsi (8 sks) 

Untuk bisa mengikuti mata kuliah Tugas Akhir, maka setiap mahasiswa sudah harus memenuhi persyaratan sebagai berikut.

1.  Untuk prasyarat Seminar Proposal Skripsi: 

    1.  Minimum lulus 80 sks. 
    2.  Melengkapi persyaratan akademik lainnya, sesuai pertimbangan Kepala Program Studi. 

2.  Untuk prasyarat Belajar Di Luar Kampus : 

    1.  Minimum lulus 80 sks. 
    2.  Minimal mendapatkan nilai C pada Mata Kuliah yang sesuai dengan Setting Magang yang dipilih atau berdasarkan syarat khusus lainnya yang ditetapkan oleh koordinator magang. 
    3.  Melengkapi persyaratan akademik lainnya, sesuai pertimbangan Kepala Program Studi. 

3.  Untuk prasyarat Skripsi: 

    1.  Telah menyelesaikan beban belajar 100 sks. 

    2.  Telah dinyatakan lulus dalam mata kuliah Seminar Proposal Skripsi dengan nilai minimal C. 

    3.  Melengkapi persyaratan akademik lainnya, sesuai pertimbangan Kepala Program Studi. 

## **Belajar Di Luar Kampus**

Kegiatan Belajar Di Luar Kampus dilakukan untuk mengakomodasi kegiatan MBKM (Merdeka Belajar Kampus Merdeka). Mahasiswa diberikan hak untuk mengikuti proses belajar mengajar diluar prodi Psikologi Universitas YARSI. Benttuk kegiatan pembelajarannya diantaranya: 

1.  Magang 
2.  Pertukaran Mahassiwa 
3.  Penelitian/Riset 
4.  Asistensi Mengajar di Satuan Pendidikan 
5.  Proyek Kemanusiaan 
6.  Kegiatan wirausaha 
7.  Studi/proyek Independen 
8.  Membangun desa/Kuliah Kerja Nyata Tematik 

Kegiatan ini bisa dimulai di semester lima. Mahasiswa boleh memilih mengikuti kegiatan ini atau tetap melakukan perkuliahan biasa di prodi Psikologi Universitas YARSI.

::: callout-caution
**Kegiatan ini harus harus disetujui oleh PA dan Prodi Psikologi untuk menyesuaikan kegiatan tersebut dengan Capaian Pembelajaran Prodi.**
:::

Kegiatan belajar di luar kampus ini akan dikonversikan sebanyak 20 SKS pada satu semester.

::: callout-caution
**Kegiatan yang akan dikonversi hanyalah kegiatan yang telah disetujui oleh PA dan Prodi Psikologi Universitas YARSI.**
:::

## **Seminar Proposal Skripsi**

Seminar Proposal Skripsi adalah tahap awal yang harus dilalui oleh mahasiswa untuk kemudian menyelesaikan skripsi. Di dalam mata kuliah ini, mahasiswa akan mendapat bimbingan intensif oleh dosen yang ditunjuk sebagai Pembimbing mengenai proses penyusunan proposal skripsi. Mahasiswa yang dianggap sudah memenuhi persyaratan yang dibutuhkan, diperkenankan untuk mengambil mata kuliah Seminar Proposal.

Prosedur pelaksanaan Seminar Proposal Skripsi, yang di dalamnya meliputi: 

1.  Program Studi mengumumkan pembukaan Mata Kuliah Seminar Proposal Skripsi pada tahun berjalan. 
2.  Mahasiswa mengajukan untuk ikut dalam mata kuliah dengan mengisi formulir pendaftaran dan pengajuan topik penelitian. 
3.  Kepala Program Studi bersama dengan anggota Komite Skripsi yang ditunjuk pada tahun berjalan melakukan proses evaluasi terkait persyaratan akademik dan usulan topik penelitian. 
4.  Komite Skripsi melakukan penunjukan Dosen Pembimbing Proposal dan mengumumkan kepada mahasiswa. 
5.  Mahasiswa memulai proses bimbingan penyusunan proposal penelitian. 
6.  Pada waktu yang ditentukan, mahasiswa harus menjalani ujian seminar yang dapat diselenggarakan dan bisa bersifat terbuka maupun tertutup sesuai dengan kebijakan yang berlaku. 
7.  Ujian seminar tahap pertama adalah evaluasi mengenai Bab I (pendahulan dan latar belakang) dalam proposal. Ujian seminar tahap akhir adalah evaluasi keseluruhan isi proposal dari Bab I-III (Pendahuluan-Metode Penelitian). 
8.  Di akhir penyelenggaraan mata kuliah, mahasiswa mendapatkan ketetapan kelulusan seminar proposal oleh komisi penguji seminar. Apabila mahasiswa dinyatakan lulus (dengan nilai minimum C), maka mahasiswa bisa melanjutkan proposal untuk dijadikan sebagai Skripsi. Namun apabila mahasiswa dinyatakan tidak lulus, maka mahasiswa diharuskan untuk mengulang mata kuliah Seminar Proposal Skripsi. 

## **Skripsi**

Apabila mahasiswa dinyatakan lulus dalam mata kuliah Seminar Proposal Penelitian/Teknik Penyusunan Skripsi, maka ia diperkenankan untuk melanjutkan proposal yang diajukan sebagai skripsi. Untuk pengajuan skripsi, proses yang dilakukan meliputi: 

1.  Kepala Program Studi mengumumkan pembukaan Mata Kuliah Skripsi pada tahun berjalan. 
2.  Mahasiswa mengajukan untuk ikut dalam mata kuliah dengan mengisi formulir pendaftaran dan pengajuan proposal penelitian. 
3.  Kepala Program Studi bersama dengan anggota Komite Skripsi yang ditunjuk pada tahun berjalan melakukan proses evaluasi terkait persyaratan akademik dan usulan topik penelitian. 
4.  Komite Skripsi melakukan penunjukan Dosen Pembimbing Skripsi dan mengumumkan kepada mahasiswa. 
5.  Mahasiswa memulai proses bimbingan skripsi. 
6.  Pada waktu yang ditentukan, mahasiswa harus menjalani ujian forum dan ujian sidang skripsi. 

## **Ujian Forum/Seminar Hasil**

1.  Ujian forum skripsi diselenggarakan apabila mahasiswa sudah dianggap selesai mengerjakan pengambilan data dan analisis akhir. 
2.  Dalam ujian forum, peserta ujian diwajibkan mengenakan kemeja putih lengan panjang, berdasi, celana panjang hitam dan bagi peserta ujian wanita diwajibkan memakai busana muslimah dengan atasan putih dan rok hitam. 
3.  Di dalam ujian forum skripsi, terdapat dosen pembahas, mahasiswa pembahas, dan notulis. 
4.  Hasil dari ujian forum adalah perbaikan skripsi sesuai dengan masukan selama proses ujian. 
5.  Apabila mahasiswa sudah menyelesaikan perbaikan ujian forum skripsi dan mendapat persetujuan dari Dosen Pembimbing maupun Dosen Pembahas Forum, maka mahasiswa diperkenankan untuk maju ke tahap Ujian Sidang Skripsi. 

## **Ujian Skripsi**

1.  Syarat untuk mengikuti ujian sidang skripsi adalah: 
    a.  Sudah menyerahkan draf skripsi final pasca ujian forum 
    b.  Nilai seluruh mata kuliah di luar skripsi sudah diselesaikan 
    c.  Tidak memiliki jabatan sebagai pengurus aktif organisasi kemahasiswaan 
2.  Untuk maju ke Ujian Sidang Skripsi, mahasiswa diharuskan mengisi Formulir Permohonan Ujian Skripsi yang wajib ditandatangani dan disetujui oleh Pembimbing Akademik. 
3.  Bagian Akademik dan Komite Skripsi akan menilai kelayakan mahasiswa ybs untuk maju ke dalam Sidang Skripsi. 
4.  Apabila memenuhi syarat, maka berikutnya akan ditentukan jadwal ujian dan tim penguji skripsi. 
5.  Dalam sidang skripsi, peserta ujian diwajibkan mengenakan kemeja putih lengan panjang, berdasi, celana panjang hitam dan bagi peserta ujian wanita diwajibkan memakai busana muslimah dengan atasan putih dan rok hitam. 
6.  Sidang skripsi diselenggarakan secara tertutup dan dihadiri oleh Dosen Penguji Skripsi, Dosen Pembimbing Ilmu dan Agama, serta Notulis. 
7.  Di akhir penyelenggaraan sidang skripsi, mahasiswa mendapatkan ketetapan kelulusan oleh komisi penguji skripsi. 
8.  Apabila dinyatakan tidak lulus, maka mahasiswa diharuskan untuk mengulang sidang skripsi sesuai dengan batas waktu yang ditentukan. 
9.  Mahasiswa yang dinyatakan lulus dengan perbaikan, wajib untuk melakukan perbaikan skripsi sesuai rekomendasi komisi penguji pada batas waktu yang ditentukan sebelum mengikuti Yudisium. 
10. Apabila mahasiswa dinyatakan lulus tanpa perbaikan, maka mahasiswa tersebut dinyatakan sudah memenuhi syarat sebagai Sarjana Psikologi dan bisa mengikuti Yudisium.

## **Penyelesaian dan Keberhasilan Studi**

1.  Syarat untuk dapat dinyatakan lulus sebagai Sarjana Psikologi dari Fakultas Psikologi Universitas YARSI dan diperkenankan mengikuti Yudisium, maka mahasiswa sudah harus menyelesaikan minimum 144 sks terdiri dari: 10 sks mata kuliah pilihan, 20-40 sks belajar di luar kampus, 8 sks skripsi, dan sisanya adalah sks mata kuliah wajib. 
2.  Penyelesaian studi dapat dilakukan apabila mahasiswa telah memenuhi ketentuan SKS pada poin 1, dan memiliki IPK \>/= 2,50 dengan nilai paling rendah adalah C (tidak ada nilai di bawah C, D, E, ataupun T/TL.) 
3.  Yudisium adalah upacara pengesahan sebagai Sarjana Psikologi yang di dalamnya akan diumumkan mengenai Nilai Skripsi, IPK, dan Predikat Kelulusan. Yudisium dapat diselenggarakan beberapa periode dalam satu semester, sesuai dengan kebutuhan Program Studi. 
4.  Masa dan beban belajar program pendidikan S1 Psikologi Universitas YARSI paling lama 7 (tujuh) tahun akademik. Keberhasilan studi dinilai untuk menentukan penyelesaian studi akan dilakukan pada akhir semester VIII sampai X. 
5.  Perpanjangan studi setiap semesternya dapat diberikan apabila yang bersangkutan belum dapat menyelesaikan studinya di tahun kelima (semester X) dengan mengajukan permohonan tertulis. Perpanjangan studi diberikan untuk satu semester dan maksimal diberikan hingga sebanyak empat kali (semester XI, XII, XII, XIV). 

### **Penilaian Akhir Program Studi** {.unnumbered}

Predikat kelulusan merupakan penghargaan akademik atas prestasi yang diperoleh seorang mahasiswa selama mengikuti perkuliahan di Universitas YARSI. Ketentuannya adalah sebagai berikut:

| Predikat Kelulusan          |     IPK     | Ketentuan                   |
|:----------------------------|:-----------:|-----------------------------|
| *Cum Laude* (dengan pujian) | 3,51 - 4,00 | Masa studi maksimum 4 tahun |
| Sangat memuaskan            | 3,01 - 3,50 |                             |
| Memuaskan                   | 2,76 - 3,00 |                             |
| Lulus                       | 2,00 - 2,75 |                             |

### **Gelar Akademik** {.unnumbered}

1.  Pada ijazah, dicantumkan gelar akademik, nama fakultas, program studi dan tanggal wisuda secara lengkap. 
2.  Penerbitan ijazah disesuaikan dengan tanggal wisuda. 

Gelar akademik lulusan Fakultas Psikologi Universitas YARSI adalah Sarjana Psikologi atau S. Psi. Selain ijazah, mahasiswa juga akan mendapatkan SKPI (Surat Keterangan Pendamping Ijazah). Ketentuan mengenai SKPI akan diatur dalam ketentuan terpisah. 

## **Wisuda** 

1.  Wisuda adalah upacara akademik berupa Sidang Terbuka Senat Akademik Universitas YARSI yang dilaksanakan dalam rangka penyerahan ijazah kepada para lulusan. 
2.  Sebelum diwisuda, lulusan harus sudah memenuhi semua persyaratan administrasi. 
3.  Daftar nama lulusan tiap wisuda ditetapkan dengan Keputusan Rektor. 
4.  Rektor dapat menentukan lulusan terbaik berdasarkan perolehan sks, predikat kelulusan, Indeks Prestasi Kumulatif (IPK), lama studi, aktivitas yang menunjang dan perilaku. Kepada lulusan terbaik tersebut diberikan penghargaan prestasi akademik pada saat wisuda. 

Persyaratan untuk mengikuti wisuda adalah : 

1.  Telah dinyatakan lulus dalam yudisium. 
2.  Telah memenuhi semua kewajiban (keuangan, perpustakaan, dan administrasi). 
3.  Mendaftarkan diri sesuai dengan ketentuan yang berlaku.
