# KURIKULUM {.unnumbered}

## Penyusunan Kurikulum Program Studi Psikologi Universitas YARSI

Dalam upaya melakukan kualifikasi terhadap lulusan perguruan tinggi di Indonesia, pemerintah telah menerbitkan Perpres No. 08 tahun 2012 tentang **Kerangka Kualifikasi Nasional Indonesia (KKNI)** dan lampirannya yang menjadi **acuan dalam penyusunan capaian pembelajaran lulusan dari setiap jenjang pendidikan secara nasional. Selain Perpres tersebut terdapat UU PT** No. 12 Tahun 2012 **serta Permenristekdikti No 44 tahun 2015 tentang Standar Nasional Perguruan Tinggi (SNPT) yang mengatur proses pendidikan di Perguruan Tinggi.**

Perpres No. 08 tahun 2012 dan UU PT No. 12 Tahun 2012 Pasal 29 ayat (1), (2), dan (3) telah berdampak pada kurikulum dan pengelolaannya di setiap program. Kurikulum yang pada awalnya mengacu pada pencapaian kompetensi menjadi mengacu pada **capaian pembelajaran (*learning outcomes*).** Selain itu, secara khusus kurikulum pendidikan psikologi juga mengacu pada hasil kesepakatan Kolokium Psikologi Indonesia dari Asosiasi Penyelenggara Pendidian Tinggi Psikologi Indonesia (AP2TPI). 

Secara umum, tujuan umum program Sarjana Psikologi berdasarkan hasil Kolokium AP2TPI adalah menghasilkan Sarjana Psikologi yang mampu: 

1.  Menunjukkan adanya integritas moral yang tinggi, menghargai harkat dan martabat manusia secara profesional dan bertanggung jawab. 
2.  Memahami konsep dan teori psikologi secara universal dan lokal secara mumpuni. 
3.  Menerapkan dan mengaplikasikan kaidah-kaidah proses berpikir ilmiah maupun praktikal sesuai dengan ketentuan Kode Etik Psikologi Indonesia. 
4.  Memecahkan masalah psikologis pada individu, kelompok, organisasi, dan masyarakat, tanpa membedakan suku, agama, ras, tingkat usia, jenis kelamin, status sosial-ekonomi budaya. 

Mengacu pada kesepakatan kolokium, standar nasional pendidikan tinggi, serta visi misi dari fakultas, maka disusunlah tujuan pembelajaran program S1 Psikologi. Kurikulum ini juga disempurnakan dengan dengan Surat Keputusan Rektor Universitas YARSI No. 013/INT/SK/REK/UY/VI/2022 mengenai penetapan Panduan Penyusunan Kurikulum Merdeka Belajar Kampus Merdeka Berbasis *Outcome Based Education*. Oleh karena itu, Mahasiswa dapat mengikuti kegiatan MBKM atau dalam kurikulum prodi psikologi disebut Belajar Di Luar Kampus dalam periode **semester lima hingga semester tujuh.**

## Profil Lulusan

**Profil lulusan Universitas YARSI:**

“Insan Intelektual Islami yang memiliki kepribadian Islami, memiliki pengetahuan integratif dengan nilai keislaman, dan berketerampilan sesuai ajaran Agama Islam.” 

**Profil Lulusan Program Studi S1 Psikologi Universitas YARSI**

Sarjana psikologi yang memiliki kepribadian Islami, terampil dalam menyelesaikan berbagai persoalan psikologi melalui analisis ilmiah yang didasarkan pada pengetahuan akan aspek-aspek biopsikososial dari perilaku serta tinjauannya dalam Islam, dan mampu menjalankan peran di masyarakat sebagai: 

1.  Tenaga Kerja di bidang Sumber Daya Manusia, Komunitas dan Pendidikan 
2.  Konsultan 
3.  Penulis/*content-creator/influencer*
4.  Konselor; 
5.  Peneliti Tingkat Dasar 
6.  Asisten Psikolog 
7.  Pelaku Usaha Mandiri 

**Tujuan Pendidikan Program Studi S1 Psikologi Universitas YARSI:**

Menghasilkan Sarjana Psikologi yang mampu: 

1.  Menunjukkan kepekaan dan kepedulian dalam isu-isu aktual di masyarakat dalam kaitannya dengan aspek biopsikososial, budaya, dan agama. 
2.  Menguasai pengetahuan dasar psikologi; yang meliputi teori fungsi psikologi, psikologi klinis, psikologi pendidikan dan perkembangan, psikologi sosial, psikologi industri, psikologi kesehatan, beserta seperangkat pengetahuan pendukung, yang terdiri dari metode penelitian, intervensi dasar psikologi, dan psikodiagnostik. 
3.  Menerapkan teknik pengamatan objektif; seperti observasi, wawancara, dan administrasi psikodiagnostik untuk membantu memahami dinamika tingkah laku manusia, baik individu, kelompok, maupun organisasi berdasarkan sudut pandang biopsikososial, budaya, dan agama. 
4.  Melakukan upaya pemberian bantuan (intervensi) untuk menyelesaikan permasalahan di masyarakat melalui pendekatan psikologi yang mempertimbangkan aspek biopsikososial, budaya, dan agama sejalan dengan kewenangannya di dalam kode etik profesi dan berdasarkan nilai-nilai Islami. 

## Capaian Pembelajaran

Capaian pembelajaran (*learning outcome*) Program Studi Psikologi (S1) Fakultas Psikologi Universitas YARSI dirumuskan dengan mengacu pada Kerangka Kualifikasi Nasional Indonesia (KKNI), kesepakatan AP2TPI, hasil *tracer study*, dan hasil diskusi internal di fakultas. Berdasarkan Deskripsi Generik Level 6 pada KKNI (PP RI Nomor 8 Tahun 2012), capaian pembelajaran minimal untuk jenjang pendidikan sarjana adalah: 

1.  Mampu mengaplikasikan bidang keahliannya dan memanfaatkan ilmu pengetahuan, teknologi, dan/atau seni pada bidangnya dalam penyelesaian masalah serta mampu beradaptasi terhadap situasi yang dihadapi; 
2.  Menguasai konsep teoritis bidang pengetahuan tertentu secara umum dan konsep teoritis bagian khusus dalam bidang pengetahuan tersebut secara mendalam, serta mampu memformulasikan penyelesaian masalah prosedural; 
3.  Mampu mengambil keputusan yang tepat berdasarkan analisis informasi dan data, dan mampu memberikan petunjuk dalam memilih berbagai alternatif solusi secara mandiri dan kelompok; 
4.  Bertanggung jawab pada pekerjaan sendiri dan dapat diberi tanggung jawab atas pencapaian hasil kerja organisasi. 

Berdasarkan Permenristek Dikti No.44 Tahun 2015 mengenai standar kompetensi lulusan, maka disampaikan bahwa capaian pembelajaran dirumuskan ke dalam empat domain, yaitu keterampilan umum, sikap, keterampilan khusus, dan pengetahuan. Untuk domain keterampilan umum dan sikap, maka dirumuskan sesuai dengan Lampiran SN Dikti dan mengacu pada kesepakatan di level Universitas YARSI. Untuk keterampilan khusus dan pengetahuan, maka capaian pembelajaran dirumuskan berdasarkan hasil kolokium AP2TPI dan juga hasil diskusi internal Fakultas. 

Berikut adalah capaian pembelajaran S1 Psikologi Fakultas Psikologi Universitas YARSI: 

```{=html}
<table style="height: 447px; width: 630px;">
<tbody>
<tr>
<td style="width: 61.7031px; background-color: lightgreen;">
<p><strong>Kode</strong></p>
</td>
<td style="width: 61.7031px; background-color: lightgreen;"><strong>Capaian Pembelajaran</strong></td>
</tr>
<tr style="background-color: lightgreen;">
<td style="width: 609px;" colspan="2">
<p><strong>PENGETAHUAN (P)</strong></p>
</td>
</tr>
<tr>
<td style="width: 61.7031px;">P1</td>
<td style="width: 547.297px;">Memiliki pengetahuan mengenai ajaran dasar Islam meliputi akidah, akhlak dan ibadah serta mengintegrasikannya ke dalam ilmu psikologi dengan berdasarkan sumber dan rujukan yang sahih dan ilmiah</td>
</tr>
<tr>
<td style="width: 61.7031px;">P2</td>
<td style="width: 547.297px;">Menguasai konsep dasar teori-teori psikologi untuk menggambarkan dan menganalisis berbagai perilaku dan gejala psikologi pada individu, kelompok, organisasi, dan komunitas; mencakup sejarah aliran dan perspektif psikologi, biopsikologi, proses &amp; fungsi mental, teori kepribadian, ilmu perkembangan manusia, ilmu kesehatan mental, psikopatologi, hubungan manusia dan lingkungan sosialnya, serta psikologi industri &amp; organisasi.</td>
</tr>
<tr>
<td style="width: 61.7031px;">P3</td>
<td style="width: 547.297px;">Menguasai metode penelitian di bidang psikologi yang meliputi desain, pengolahan data, etika, dan analisis hasil penelitian sesuai dengan prinsip metodologi penelitian dasar, mencakup pendekatan kuantitatif dan statistika, pendekatan kualitatif serta pendekatan psikometri</td>
</tr>
<tr>
<td style="width: 61.7031px;">P4</td>
<td style="width: 547.297px;">Menguasai konsep dasar asesmen psikologis meliputi observasi, wawancara, serta pengukuran kepribadian, minat, bakat dan intelegensi</td>
</tr>
<tr>
<td style="width: 61.7031px;">P5</td>
<td style="width: 547.297px;">Menguasai konsep intervensi psikologi non klinis, yang meliputi intervensi individual (konseling) dan intervensi kelompok (pelatihan, psikoedukasi dan intervensi sosial</td>
</tr>
<tr>
<td style="width: 61.7031px;">P6</td>
<td style="width: 547.297px;">Menguasai prinsip literasi data (tata cara memperoleh data dan informasi yang sahih serta mengolah data dengan memanfaatkan teknologi informasi) dan literasi teknologi (tata cara pemanfaatan teknologi dalam menyampaikan gagasan)</td>
</tr>
<tr style="background-color: lightgreen;">
<td style="width: 609px;" colspan="2">
<p><strong>SIKAP (S)</strong></p>
</td>
</tr>
<tr>
<td style="width: 61.7031px;">S1</td>
<td style="width: 547.297px;">Menunjukkan nilai-nilai keislaman dalam kehidupan akademis dan nonakademis (fokus pada keislaman)</td>
</tr>
<tr>
<td style="width: 61.7031px;">S2</td>
<td style="width: 547.297px;">Berperan dalam peningkatan mutu kehidupan bermasyarakat, berbangsa, dan bernegara dengan rasa kepedulian, tanggung jawab, dan nasionalisme sesuai dengan keahliannya (fokus pada masyarakat)</td>
</tr>
<tr>
<td style="width: 61.7031px;">S3</td>
<td style="width: 547.297px;">Menginternalisasi nilai, norma, dan etika serta semangat kemandirian dan kewirausahaan dalam upaya mencapai keberhasilan sesuai dengan minat dan keahliannya.</td>
</tr>
<tr style="background-color: lightgreen;">
<td style="width: 609px;" colspan="2">
<p><strong>KETERAMPILAN&nbsp;UMUM (KU)</strong></p>
</td>
</tr>
<tr>
<td style="width: 61.7031px;">KU1</td>
<td style="width: 547.297px;">Mampu menerapkan prinsip-prinsip, tata cara, dan etika ilmiah dalam hal pemikiran, pengembangan, implementasi, dan evaluasi penggunaan iptek dengan memperhatikan nilai humaniora sesuai bidang keahlian psikologi, dalam bentuk skripsi atau laporan tugas akhir yang diunggah dalam laman perguruan tinggi</td>
</tr>
<tr>
<td style="width: 61.7031px;">KU2</td>
<td style="width: 547.297px;">Mampu bekerja secara mandiri maupun kelompok, mengembangkan diri, memelihara dan mengembangkan jaringan kerja, serta melakukan evaluasi dan supervisi terhadap kerja kelompoknya secara bertanggung jawab</td>
</tr>
<tr>
<td style="width: 61.7031px;">KU3</td>
<td style="width: 547.297px;">Mampu menerapkan keterampilan menjadi imam shalat, memberikan khutbah, melakukan perawatan jenazah membaca, menghafal, dan memahami Al Qur'an khususnya juz 30, serta mengkaitkan isi Al Qur'an dengan bidang keilmuan psikologi</td>
</tr>
<tr>
<td style="width: 61.7031px;">KU4</td>
<td style="width: 547.297px;">Mampu menggunakan minimal satu bahasa internasional untuk komunikasi lisan dan tulis</td>
</tr>
<tr style="background-color: lightgreen;">
<td style="width: 609px;" colspan="2">
<p><strong>KETERAMPILAN KHUSUS (KK)</strong></p>
</td>
</tr>
<tr>
<td style="width: 61.7031px;">KK1</td>
<td style="width: 547.297px;">Mampu merancang, melaksanakan, dan melaporkan penelitian kuantitatif dan kualitatif, termasuk menuangkan pemikiran dan gagasan konseptual, memperoleh dan mengolah data penelitian maupun informasi dalam konteks psikologi, pengembangan instrumen pengukuran psikologi, serta penulisan karya tulis ilmiah, melalui pemanfaatan teknologi, dengan metodologi dan prinsip keilmuan yang tepat dan berlandaskan Kode Etik Psikologi Indonesia</td>
</tr>
<tr>
<td style="width: 61.7031px;">KK2</td>
<td style="width: 547.297px;">Mampu merancang, melaksanakan, dan melaporkan program intervensi dalam upaya pemecahan masalah psikologis dalam ruang lingkup individu, kelompok, organisasi, dan masyarakat, berdasarkan gagasan teoretis, serta pemerolehan dan analisis data yang tepat, melalui pemanfaatan teknologi, dengan metodologi dan prinsip keilmuan yang tepat dan berlandaskan Kode Etik Psikologi Indonesia</td>
</tr>
<tr>
<td style="width: 61.7031px;">KK3</td>
<td style="width: 547.297px;">Mampu menganalisis konsep-konsep psikologi berdasarkan perspektif islam sesuai dengan kaidah ilmiah dan sumber-sumber keislaman yang sahih</td>
</tr>
<tr>
<td style="width: 61.7031px;">KK4</td>
<td style="width: 547.297px;">Mampu beradaptasi, bekerja sama, berkreasi, berkontribusi, dan berinovasi dalam menerapkan ilmu pengetahuan di bidang psikologi pada kehidupan bermasyarakat serta berperan sebagai warga dunia yang berwawasan global</td>
</tr>
</tbody>
</table>
```

## Prosedur Penilaian Pembelajaran

Berdasarkan **Panduan Penyusunan Kurikulum Pendidikan Tinggi yang disusun oleh Kementerian Riset, Teknologi, dan Pendidikan Tinggi (2016)**, terdapat beberapa hal yang perlu diperhatikan dalam penilaian pembelajaran. 

Yang dimaksud dalam tahap penilaian pembelajaran adalah tahap penilaian proses dan hasil pembelajaran. Penilaian capaian pembelajaran dilakukan pada ranah sikap, pengetahuan dan keterampilan secara rinci dijelaskan sebagai berikut: 

1.  **Penilaian ranah sikap** dilakukan melalui observasi, penilaian diri, penilaian antar mahasiswa (mahasiswa menilai kinerja rekannya dalam satu bidang atau kelompok), dan penilaian aspek pribadi yang menekankan pada aspek beriman, berakhlak mulia, percaya diri, disiplin dan bertanggung jawab dalam berinteraksi secara efektif dengan lingkungan sosial, alam sekitar, serta dunia dan peradabannya. 
2.  **Penilaian ranah pengetahuan** melalui berbagai bentuk tes tulis dan tes lisan yang secara teknis dapat dilaksanakan secara langsung maupun tidak langsung. Secara langsung maksudnya dalah dosen dan mahasiswa bertemu secara tatap muka saat penilaian, misalnya saat seminar dan ujian skripsi. Sedangkan secara tidak langsung, misalnya menggunakan lembar-lembar soal ujian tulis. 
3.  **Penilaian ranah keterampilan** melalui penilaian kinerja yang dapat diselenggarakan melalui praktikum, praktek, simulasi, praktek lapangan, dll. yang memungkinkan mahasiswa untuk dapat meningkatkan kemampuan ketrampilannya. 

Prinsip dalam penilaian adalah: 

1.  **Edukatif,** merupakan penilaian yang memotivasi mahasiswa agar mampu: 
    a.  memperbaiki perencanaan dan cara belajar; dan
    b.  meraih capaian pembelajaran lulusan. Dalam prosesnya diwujudkan dalam umpan balik yang diberikan kepada mahasiswa untuk setiap tugas dan ujian yang diberikan. 
2.  **Otentik,** merupakan penilaian yang berorientasi pada proses belajar yang berkesinambungan dan hasil belajar yang mencerminkan kemampuan mahasiswa pada saat proses pembelajaran berlangsung. Oleh karena itu, setiap dosen wajib memasukkan hasil penilaian akhir maupun proses belajar di dalam komponen penilaian. 
3.  **Objektif,** merupakan penilaian yang didasarkan pada standar yang disepakati antara dosen dan mahasiswa, serta bebas dari pengaruh subjektivitas penilai dan yang dinilai. Hal ini diwujudkan dari adanya poin penilaian yang jelas berdasarkan indikator yang ada sesuai capaian pembelajaran. Indikator penilaian ini kemudian dituangkan dalam sebuah instrumen penilaian beserta penyekorannya. 
4.  **Akuntabel,** merupakan penilaian yang dilaksanakan sesuai dengan prosedur dan kriteria yang jelas, disepakati pada awal kuliah, dan dipahami oleh mahasiswa. Dengan demikian, setiap dosen wajib memberikan sosialisasi terkait rincian penilaian yang akan diberikan. 
5.  **Transparan,** merupakan penilaian yang prosedur dan hasil penilaiannya dapat diakses oleh semua pemangku kepentingan. Oleh karena itu, hasil penilaian wajib untuk menyertakan komponen penilaian dan rinciannya kemudian dipublikasi melalui sistem informasi akademik yang dapat diakses oleh mahasiswa, dosen, Kepala Program Studi, maupun Staf Bagian Akademik. 

### Instrumen Penilaian {.unnumbered}

Instrumen Penilaian dapat berbentuk sebagai berikut: 

1.  **Soal Ujian Tulis**

    Soal ujian tulis ditujukan untuk menilai kedalaman pengetahuan mahasiswa sesuai dengan capaian pembelajaran dan materi pembelajaran. Ujian tulis dapat berupa soal pilihan berganda, menjodohkan, ataupun esai. Setiap soal ujian tulis yang ditujukan untuk penilaian pembelajaran di tengah dan di akhir semester, wajib disusun berdasarkan *blueprin*t soal serta diverifikasi oleh dosen dan Kepala Program Studi, dan memiliki relevansi dengan capaian pembelajaran domain pengetahuan yang dituju. 

2.  **Rubrik**

    Rubrik merupakan panduan penilaian yang menggambarkan kriteria yang diinginkan dalam menilai atau memberi tingkatan dari hasil kinerja belajar mahasiswa. Rubrik terdiri dari dimensi yang dinilai dan kriteria kemampuan hasil belajar mahasiswa ataupun indikator capaian belajar mahasiswa. Tujuan penilaian menggunakan rubrik adalah memperjelas dimensi dan tingkatan penilaian dari capaian pembelajaran mahasiswa. Selain itu, rubrik diharapkan dapat menjadi pendorong atau motivator bagi mahasiswa untuk mencapai capaian pembelajarannya. Contoh rubrik dapat dilihat pada bagian lampiran. 

3.  **Portofolio**

    Penilaian portofolio merupakan penilaian berkelanjutan yang didasarkan pada kumpulan informasi yang menunjukkan perkembangan capaian belajar mahasiswa dalam satu periode tertentu. Informasi tersebut dapat berupa karya mahasiswa dari proses pembelajaran yang dianggap terbaik atau karya mahasiswa yang menunjukkan perkembangan kemampuannya untuk mencapai capaian pembelajaran. 

    Macam penilaian portofolio adalah sebagai berikut: 

    a.  Portofolio perkembangan, berisi koleksi artefak karya mahasiswa yang menunjukkan kemajuan pencapaian kemampuannya sesuai dengan tahapan belajar yang telah dijalani. 
    b.  Portofolio pamer/*showcase* berisi artefak karya mahasiswa yang menunjukkan hasil kinerja belajar terbaiknya. 
    c.  Portofolio komprehensif, berisi artefak seluruh hasil karya mahasiswa selama proses pembelajaran.

## Distribusi Mata Kuliah Per Semester

Distribusi mata kuliah dirancang agar mahasiswa yang memenuhi persyaratan dapat menempuh kuliah selama 4 tahun. Distribusi mata kuliah untuk tiap semester dan kuliah prasyarat yang harus ditempuh, dapat dilihat pada tabel di bawah ini. 

```{=html}
<table style="height: 425px; width: 823px;">
<tbody>
<tr style="height: 43.9219px;">
<td style="width: 70px; height: 43.9219px; text-align: center;"><strong>Semester</strong></td>
<td style="width: 557px; height: 43.9219px; text-align: center;" colspan="8"><strong>Struktur Kurikulum</strong></td>
<td style="width: 70px; height: 43.9219px; text-align: center;"><strong>SKS (Wajib)</strong></td>
</tr>
<tr style="height: 22px;">
<td style="width: 70px; height: 22px;">VIII</td>
<td style="width: 70px; height: 22px; background-color: #f5a627;">Kapita Selekta Psikologi Islam (1)</td>
<td style="width: 58.7812px; height: 22px; background-color: lightblue;">Skripsi (8)</td>
<td style="width: 121.219px; height: 22px; background-color: lightblue;">3 MK Pilihan</td>
<td style="width: 27px; height: 22px;">&nbsp;</td>
<td style="width: 70px; height: 22px;">&nbsp;</td>
<td style="width: 70px; height: 22px;">&nbsp;</td>
<td style="width: 70px; height: 22px;">&nbsp;</td>
<td style="width: 70px; height: 22px;">&nbsp;</td>
<td style="width: 70px; height: 22px; text-align: right;">9</td>
</tr>
<tr style="height: 22px;">
<td style="width: 70px; height: 22px;">VII</td>
<td style="width: 70px; height: 22px; background-color: #f5a627;">Kuliah Kerja Nyata (3)</td>
<td style="width: 58.7812px; height: 22px; background-color: lightblue;">Seminar Proposal Skripsi (2)</td>
<td style="width: 121.219px; height: 22px; background-color: lightblue;">9 MK Pilihan</td>
<td style="width: 27px; height: 22px;">&nbsp;</td>
<td style="width: 70px; height: 22px;">&nbsp;</td>
<td style="width: 70px; height: 22px;">&nbsp;</td>
<td style="width: 70px; height: 22px;">&nbsp;</td>
<td style="width: 70px; height: 22px;">&nbsp;</td>
<td style="width: 70px; height: 22px; text-align: right;">5</td>
</tr>
<tr style="height: 22px;">
<td style="width: 70px; height: 22px;">VI</td>
<td style="width: 70px; height: 22px; background-color: lightgreen;">Belajar di Luar Kampus/Magang Mandiri</td>
<td style="width: 58.7812px; height: 22px;">&nbsp;</td>
<td style="width: 121.219px; height: 22px;">&nbsp;</td>
<td style="width: 27px; height: 22px;">&nbsp;</td>
<td style="width: 70px; height: 22px;">&nbsp;</td>
<td style="width: 70px; height: 22px;">&nbsp;</td>
<td style="width: 70px; height: 22px;">&nbsp;</td>
<td style="width: 70px; height: 22px;">&nbsp;</td>
<td style="width: 70px; height: 22px; text-align: right;">20</td>
</tr>
<tr style="height: 22px;">
<td style="width: 70px; height: 22px;">V</td>
<td style="width: 70px; height: 22px; background-color: #f5a627;">Pengantar Psi. Islam (1)</td>
<td style="width: 58.7812px; height: 22px; background-color: lightblue;">Psi. Kesehatan &amp; Aplikasinya (4)</td>
<td style="width: 121.219px; height: 22px; background-color: lightblue;">Asesmen dalam Organisasi (3)</td>
<td style="width: 27px; height: 22px; background-color: lightblue;">Pelatihan (3)</td>
<td style="width: 70px; height: 22px; background-color: lightblue;">Psi. Konseling (3)</td>
<td style="width: 70px; height: 22px; background-color: lightblue;">Intervensi Sosial(4)</td>
<td style="width: 70px; height: 22px; background-color: lightblue;">3 MK Pilihan</td>
<td style="width: 70px; height: 22px;">&nbsp;</td>
<td style="width: 70px; height: 22px; text-align: right;">18</td>
</tr>
<tr style="height: 22px;">
<td style="width: 70px; height: 22px;">IV</td>
<td style="width: 70px; height: 22px; background-color: #f5a627;">Agama Islam IV (1)</td>
<td style="width: 58.7812px; height: 22px; background-color: #f5a627;">Asistensi Agama Islam (1)</td>
<td style="width: 121.219px; height: 22px; background-color: lightblue;">Assesmen Kepribadian &amp; Inteligensi (6)</td>
<td style="width: 27px; height: 22px; background-color: lightblue;">Psikologi Konseling (3)</td>
<td style="width: 70px; height: 22px; background-color: lightblue;">Metodologi Penelitian Kualitatif(3)</td>
<td style="width: 70px; height: 22px; background-color: lightblue;">Psikologi &amp; Budaya (3)</td>
<td style="width: 70px; height: 22px; background-color: lightblue;">KAUP (4)</td>
<td style="width: 70px; height: 22px;">&nbsp;</td>
<td style="width: 70px; height: 22px; text-align: right;">21</td>
</tr>
<tr style="height: 22px;">
<td style="width: 70px; height: 22px;">III</td>
<td style="width: 70px; height: 22px; background-color: #f5a627;">III Agama Islam III (1)</td>
<td style="width: 58.7812px; height: 22px; background-color: lightblue;">Psi. Pendidikan (3)</td>
<td style="width: 121.219px; height: 22px; background-color: lightblue;">Metode Observasi &amp; Wawancara (4)</td>
<td style="width: 27px; height: 22px; background-color: lightblue;">Psi. Industri &amp; Organisasi (3)</td>
<td style="width: 70px; height: 22px; background-color: lightblue;">Penelitian Kuantitatif &amp; Statistika Lanjutan (4)</td>
<td style="width: 70px; height: 22px; background-color: lightblue;">Analisis Isu Sosial(2)</td>
<td style="width: 70px; height: 22px; background-color: lightblue;">Psi. Klinis &amp; Psikopatologi(4)</td>
<td style="width: 70px; height: 22px;">&nbsp;</td>
<td style="width: 70px; height: 22px; text-align: right;">21</td>
</tr>
<tr style="height: 22px;">
<td style="width: 70px; height: 22px;">II</td>
<td style="width: 70px; height: 22px; background-color: #f5a627;">Agama Islam II (1)</td>
<td style="width: 58.7812px; height: 22px; background-color: #f5a627;">Kewarganegaraan (2)</td>
<td style="width: 121.219px; height: 22px; background-color: #f5a627;">Kewirausahaan (2)</td>
<td style="width: 27px; height: 22px; background-color: lightblue;">Pengantar Asesmen Psikologi (2)</td>
<td style="width: 70px; height: 22px; background-color: lightblue;">Psi. Perkembangan (5)</td>
<td style="width: 70px; height: 22px; background-color: lightblue;">Penelitian Kuantitatif &amp; Statistika Dasar (4)</td>
<td style="width: 70px; height: 22px; background-color: lightblue;">Psi. Kepribadian(4)</td>
<td style="width: 70px; height: 22px; background-color: lightblue;">Psi. Sosial (3)</td>
<td style="width: 70px; height: 22px; text-align: right;">23</td>
</tr>
<tr style="height: 22px;">
<td style="width: 70px; height: 22px;">I</td>
<td style="width: 70px; height: 22px; background-color: #f5a627;">Agama Islam I (2)</td>
<td style="width: 58.7812px; height: 22px; background-color: #f5a627;">Pancasila (2)</td>
<td style="width: 121.219px; height: 22px; background-color: #f5a627;">B. Inggris (2)</td>
<td style="width: 27px; height: 22px; background-color: lightblue;">B.Indonesia (2)</td>
<td style="width: 70px; height: 22px; background-color: lightblue;">PPBKB (5)</td>
<td style="width: 70px; height: 22px; background-color: lightblue;">Sejarah Aliran Psikologi (3)</td>
<td style="width: 70px; height: 22px; background-color: lightblue;">Logika Penulisan Ilmiah (2)</td>
<td style="width: 70px; height: 22px; background-color: lightblue;">Pengembangan Diri &amp; Karir (2)</td>
<td style="width: 70px; height: 22px; text-align: right;">20</td>
</tr>
<tr style="height: 22px;">
<td style="width: 70px; height: 22px;">&nbsp;</td>
<td style="width: 557px; height: 22px;" colspan="8"><strong>Total (Wajib)</strong></td>
<td style="width: 70px; height: 22px; text-align: right;"><strong>137</strong></td>
</tr>
<tr style="height: 22px;">
<td style="width: 70px; height: 22px;">Ket:</td>
<td style="width: 70px; height: 22px; background-color: #f5a627;">MK Umum</td>
<td style="width: 58.7812px; height: 22px; background-color: lightblue;">MK Keilmuan</td>
<td style="width: 121.219px; height: 22px; background-color: lightgreen;">Kegiatan MBKM</td>
<td style="width: 27px; height: 22px;">&nbsp;</td>
<td style="width: 70px; height: 22px;">&nbsp;</td>
<td style="width: 70px; height: 22px;">&nbsp;</td>
<td style="width: 70px; height: 22px;">&nbsp;</td>
<td style="width: 70px; height: 22px;">&nbsp;</td>
<td style="width: 70px; height: 22px; text-align: right;">&nbsp;</td>
</tr>
</tbody>
</table>
```
