# PELAYANAN, SARANA, DAN PRASARANA BAGI MAHASISWA {.unnumbered}

## **Laboratorium Psikologi**

Laboratorium Psikologi digunakan dalam rangka mendukung sarana pembelajaran. Fakultas Psikologi dilengkapi dengan beberapa laboratorium, yaitu laboratorium eksperimen, laboratorium perkembangan, laboraturium psikologi lalu lintas, ruang observasi dan wawancara, ruang konseling, dan ruang klasikal yang digunakan untuk praktikum psikodiagnostik. Setiap ruang di laboratorium dilengkapi dengan pendingin ruangan.

Untuk laboratorium eksperimen terdapat beberapa peralatan eksperimen yang dapat digunakan untuk praktikum. Untuk laboratorium perkembangan dilengkapi dengan *one way mirror* dan peralatan bermain bagi anak-anak. Untuk ruang observasi wawancara dilengkapi dengan *one way mirror*, kamera CCTV, *headphone* dan sebuah ruang kontrol untuk memonitor pelaksanaan praktikum mahasiswa. Ruang psikologi lalu lintas dilengkapi dengan simulator mengemudi, *Hazard Perception Test, Virtual Reality (VR)*, Inquisit Lab yang berisikan perangkan EMOTIV untuk riset pembelajaran *neurofeedback* dan *Implicit Association Test*. Secara umum, sarana yang ada di laboratorium sangat menunjang keberhasilan belajar mahasiswa, terutama pada mata kuliah yang membutuhkan kegiatan praktikum.

## **Perpustakaan**

Universitas YARSI memiliki sarana berupa satu perpustakaan yang terpusat yang dapat dimanfaatkan mahasiswa secara gratis. Perpustakaan dilengkapi dengan koleksi buku, majalah, koran dan jurnal. Perpustakaan juga menyediakan sekitar 120 unit komputer untuk mengakses *search-engine* jurnal daring, seperti EBSCO, *ProQues*t, *Kerger, Gale Cengage*, *Rehabilitation Reference Center,* dan *DynaMed*. Perpustakaan Universitas YARSI saat ini juga telah menggunakan sistem informasi berbasis *web* terbaru, yang dikenal dengan SLiMS (*Senayan Information Management System*).

Untuk melengkapi keunggulannya, perpustakaan juga sudah mulai menggunakan RFID (*Radio Frequency Identification*). RFID mempunyai beberapa keuntungan yang utama, melebihi sistem *barcode.* Sistem RFID ini telah digunakan Perpustakaan Universitas YARSI untuk koleksi buku-buku yang ada di perpustakaan. Sistem RFID ini kemudian diintegrasikan dengan SLiMS melalui entri data yang terekam didalam *Tag Reader*.

Untuk menunjang performa akademik mahasiswa, perpustakaan juga menyediakan fasilitas ruangan yang dapat digunakan secara pribadi ataupun kelompok. Ruangan tersebut di antaranya adalah ruang baca dan ruang diskusi. Terdapat pula ruangan yang dinamakan *Window of the World*, yaitu ruang yang memiliki koleksi buku baik cetak maupun digital yang terkait dengan informasi kebudayaan dari berbagai negara.

## **Bank**

Fasilitas perbankan yang ada di lingkungan Universitas YARSI terdiri dari Bank Mandiri dan Bank BRI Cabang Universitas YARSI Jakarta. Bank-bank tersebut akan memberikan pelayanan bagi warga Universitas YARSI dan masyarakat umum yang ada di sekitar Kampus Universitas YARSI. Fasilitas perbankan ini merupakan bagian dari sarana pelayanan yang turut menunjang para mahasiswa dalam melakukan pembayaran kewajiban keuangan dan hal-hal lain menyangkut perbankan.

## ***Food Court***

Kampus Universitas YARSI menyediakan *food court* yang cukup nyaman dan luas. *Food court* dilengkapi dengan fasilitas wastafel untuk mencuci tangan. *Food court* ini melayani warga Universitas YARSI dan umum.

## **Auditorium**

Auditorium merupakan sarana yang dapat digunakan untuk melakukan berbagai aktivitas dengan kapasitas orang yang besar. Universitas menyediakan Auditorium Universitas YARSI yang berdaya tampung ± 1200 orang.

## **Masjid**

Untuk kepentingan peribadatan tersedia Masjid Jami Universitas YARSI yang berada di sebelah barat kampus.

## **Klinik**

Untuk kepentingan kesehatan, tersedia klinik YARSI yang berada di sebelah timur kampus yang berdekatan dengan *food court*. 
